version: '3.2'
services:
  website:
    build:
      context: .
      dockerfile: website.dockerfile
    ports: 
      - 80:80
  unit-tests:
    volumes: 
      - "$PWD:/app"
    build: 
      context: .
      dockerfile: rspec.dockerfile
    command:
      - --pattern
      - spec/unit/*_spec.rb
        

